# Generated by Django 5.0.3 on 2024-03-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=250)),
                ('elo', models.IntegerField(default=0)),
                ('editorial', models.CharField(blank=True, default='', max_length=250)),
                ('tags', models.ManyToManyField(blank=True, to='problems.tag')),
            ],
        ),
    ]
