# Generated by Django 5.0.3 on 2024-03-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=250)),
                ('elo', models.IntegerField(default=0)),
                ('editorial', models.CharField(default='', max_length=250)),
                ('tags', models.ManyToManyField(to='base.tag')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('problems_solved', models.ManyToManyField(to='base.problem')),
            ],
        ),
    ]
