# Generated by Django 5.0.3 on 2024-03-14 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_problem_tags_alter_userinfo_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
