# Generated by Django 5.0.3 on 2024-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_profile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='editorial',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
