# Generated by Django 5.0.3 on 2024-04-09 01:51

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(default='', max_length=200)),
                ('safe_guide_name', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=200)),
                ('safe_page_name', models.CharField(default='', max_length=200)),
                ('markdown', models.TextField()),
                ('html_generated_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='learn/templates/generated'), upload_to='')),
                ('authors', models.ManyToManyField(to='accounts.profile')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.guide')),
            ],
        ),
    ]
