# Generated by Django 5.0.4 on 2024-07-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_page_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='page',
            order_with_respect_to=None,
        ),
    ]
