# Generated by Django 5.0.4 on 2024-05-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_remove_guide_safe_guide_name_and_more_squashed_0005_rename_safe_url_name_guide_url_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='toc',
            field=models.TextField(default=''),
        ),
    ]
