# Generated by Django 5.0.4 on 2024-07-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_page_page_order_alter_page_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_order']},
        ),
        migrations.AlterField(
            model_name='page',
            name='page_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('guide', 'page_order')},
        ),
    ]
