# Generated by Django 5.0.7 on 2024-07-25 19:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_alter_page_options_alter_page_page_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html_generated_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='templates/generated'), upload_to=''),
        ),
    ]
