# Generated by Django 5.0.3 on 2024-03-14 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_userstats_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 0, 23, 39, 899306, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
