# Generated by Django 5.0.3 on 2024-03-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_userinfo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
    ]
