# Generated by Django 5.0.3 on 2024-03-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_problem_editorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='problems_solved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
